const STORAGE_KEY = 'betterCrunchyrollEnabled';
const VERSION = '0.2.22';
const KEYS = { shortcuts: 'betterCrunchyrollShortcuts', autoSkipIntro: 'betterCrunchyrollAutoSkipIntro', autoSkipRecap: 'betterCrunchyrollAutoSkipRecap', autoSkipCredits: 'betterCrunchyrollAutoSkipCredits', blurUpcoming: 'betterCrunchyrollBlurUpcoming', hideUpcomingTitles: 'betterCrunchyrollHideUpcomingTitles' };
const DEFAULT_SHORTCUTS = { skip: 'KeyS', previous: 'KeyP', next: 'KeyN' };
const popupElement=document.querySelector('.popup'),toggleButton=document.getElementById('toggleButton'),versionText=document.getElementById('versionText'),logoImage=document.querySelector('.popup__logo'),settingsButton=document.getElementById('settingsButton'),mainView=document.getElementById('mainView'),settingsView=document.getElementById('settingsView'),backSettingsButton=document.getElementById('backSettingsButton'),captureHint=document.getElementById('captureHint');
let activeShortcut=null;
const shortcutButtons={skip:document.querySelector('[data-shortcut="skip"]'),previous:document.querySelector('[data-shortcut="previous"]'),next:document.querySelector('[data-shortcut="next"]')};
const shortcutLabels={skip:document.getElementById('shortcutSkip'),previous:document.getElementById('shortcutPrevious'),next:document.getElementById('shortcutNext')};
function pretty(code){const n={KeyS:'S',KeyP:'P',KeyN:'N',Escape:'Esc',Space:'Space',ArrowLeft:'←',ArrowRight:'→',ArrowUp:'↑',ArrowDown:'↓'};return n[code]||code.replace(/^Key/,'').replace(/^Digit/,'');}
function render(enabled){const on=enabled!==false;popupElement.dataset.enabled=String(on);logoImage.src=on?'icons/icon128.png':'icons/icon128-off.png';toggleButton.setAttribute('aria-checked',String(on));toggleButton.setAttribute('aria-label',on?'Disable Better Crunchyroll':'Enable Better Crunchyroll');versionText.textContent=`v${VERSION}`;}
async function load(){const stored=await chrome.storage.local.get({[STORAGE_KEY]:true,[KEYS.shortcuts]:DEFAULT_SHORTCUTS,[KEYS.autoSkipIntro]:false,[KEYS.autoSkipRecap]:false,[KEYS.autoSkipCredits]:false,[KEYS.blurUpcoming]:false,[KEYS.hideUpcomingTitles]:false});render(stored[STORAGE_KEY]);const shortcuts={...DEFAULT_SHORTCUTS,...(stored[KEYS.shortcuts]||{})};Object.entries(shortcutLabels).forEach(([k,e])=>e.textContent=pretty(shortcuts[k]));for(const [id,key] of [['autoSkipIntro',KEYS.autoSkipIntro],['autoSkipRecap',KEYS.autoSkipRecap],['autoSkipCredits',KEYS.autoSkipCredits],['blurUpcoming',KEYS.blurUpcoming],['hideUpcomingTitles',KEYS.hideUpcomingTitles]])document.getElementById(id).checked=Boolean(stored[key]);}
toggleButton.addEventListener('click',async()=>{const current=toggleButton.getAttribute('aria-checked')==='true';await chrome.storage.local.set({[STORAGE_KEY]:!current});render(!current);});
settingsButton.addEventListener('click',()=>{mainView.hidden=true;settingsView.hidden=false;});backSettingsButton.addEventListener('click',()=>{settingsView.hidden=true;mainView.hidden=false;activeShortcut=null;captureHint.hidden=true;Object.values(shortcutButtons).forEach(b=>b.classList.remove('capturing'));});
[['autoSkipIntro',KEYS.autoSkipIntro],['autoSkipRecap',KEYS.autoSkipRecap],['autoSkipCredits',KEYS.autoSkipCredits],['blurUpcoming',KEYS.blurUpcoming],['hideUpcomingTitles',KEYS.hideUpcomingTitles]].forEach(([id,key])=>document.getElementById(id).addEventListener('change',e=>chrome.storage.local.set({[key]:e.target.checked})));
Object.entries(shortcutButtons).forEach(([name,b])=>b.addEventListener('click',()=>{activeShortcut=name;captureHint.hidden=false;Object.values(shortcutButtons).forEach(x=>x.classList.remove('capturing'));b.classList.add('capturing');}));
document.addEventListener('keydown',async e=>{if(!activeShortcut)return;e.preventDefault();e.stopPropagation();if(e.code==='Escape'){activeShortcut=null;captureHint.hidden=true;Object.values(shortcutButtons).forEach(b=>b.classList.remove('capturing'));return;}if(e.ctrlKey||e.altKey||e.metaKey)return;const stored=await chrome.storage.local.get({[KEYS.shortcuts]:DEFAULT_SHORTCUTS});const shortcuts={...DEFAULT_SHORTCUTS,...(stored[KEYS.shortcuts]||{})};shortcuts[activeShortcut]=e.code;await chrome.storage.local.set({[KEYS.shortcuts]:shortcuts});shortcutLabels[activeShortcut].textContent=pretty(e.code);Object.values(shortcutButtons).forEach(b=>b.classList.remove('capturing'));activeShortcut=null;captureHint.hidden=true;},true);
chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local')load();});load();
