(() => {
  const STORAGE = { enabled: 'betterCrunchyrollEnabled', shortcuts: 'betterCrunchyrollShortcuts', autoSkipIntro: 'betterCrunchyrollAutoSkipIntro', autoSkipRecap: 'betterCrunchyrollAutoSkipRecap', autoSkipCredits: 'betterCrunchyrollAutoSkipCredits', blurUpcoming: 'betterCrunchyrollBlurUpcoming', hideUpcomingTitles: 'betterCrunchyrollHideUpcomingTitles' };
  const DEFAULTS = { shortcuts: { skip: 'KeyS', previous: 'KeyP', next: 'KeyN' }, autoSkipIntro: false, autoSkipRecap: false, autoSkipCredits: false, blurUpcoming: false, hideUpcomingTitles: false };
  const STYLE_ID = 'better-crunchyroll-v222-style';
  const LIST_SELECTOR = '.erc-episode-list-modal .erc-playable-collection.state-dt-condensed';
  let enabled = true; let observer = null; let settings = { ...DEFAULTS, shortcuts: { ...DEFAULTS.shortcuts } }; const autoSkipState = new WeakSet();
  const isTyping = (target) => { const tag = target?.tagName?.toLowerCase(); return tag === 'input' || tag === 'textarea' || tag === 'select' || target?.isContentEditable; };
  const visible = (el) => { if (!el) return false; const s = getComputedStyle(el), r = el.getBoundingClientRect(); return s.display !== 'none' && s.visibility !== 'hidden' && r.width > 0 && r.height > 0; };
  const cardEpisodeNumber = (card) => { const m = (card?.textContent || '').match(/\bE(?:pisode)?\s*(\d+)\b/i); return m ? Number(m[1]) : NaN; };
  function injectStyles(){ if(document.getElementById(STYLE_ID))return; const s=document.createElement('style'); s.id=STYLE_ID; s.textContent=`
    .erc-episode-list-modal .erc-playable-collection.state-dt-condensed > .card[data-better-crunchyroll-upcoming="true"] [class*="thumbnail-wrapper"] img{filter:blur(14px)!important;transform:scale(1.05)!important}
    .erc-episode-list-modal .erc-playable-collection.state-dt-condensed > .card[data-better-crunchyroll-upcoming="true"][data-better-crunchyroll-hide-title="true"] [class*="playable-card__title"],
    .erc-episode-list-modal .erc-playable-collection.state-dt-condensed > .card[data-better-crunchyroll-upcoming="true"][data-better-crunchyroll-hide-title="true"] [class*="title"],
    .erc-episode-list-modal .erc-playable-collection.state-dt-condensed > .card[data-better-crunchyroll-upcoming="true"][data-better-crunchyroll-hide-title="true"] h3{font-size:0!important}
    .erc-episode-list-modal .erc-playable-collection.state-dt-condensed > .card[data-better-crunchyroll-upcoming="true"][data-better-crunchyroll-hide-title="true"] [class*="playable-card__title"]::after,
    .erc-episode-list-modal .erc-playable-collection.state-dt-condensed > .card[data-better-crunchyroll-upcoming="true"][data-better-crunchyroll-hide-title="true"] [class*="title"]::after,
    .erc-episode-list-modal .erc-playable-collection.state-dt-condensed > .card[data-better-crunchyroll-upcoming="true"][data-better-crunchyroll-hide-title="true"] h3::after{content:attr(data-better-crunchyroll-episode-label);font-size:16px}
  `; (document.head||document.documentElement).appendChild(s); }
  function removeStyles(){ document.getElementById(STYLE_ID)?.remove(); }
  function findCollection(){ return Array.from(document.querySelectorAll(LIST_SELECTOR)).find(visible)||null; }
  function updateSpoilers(){ if(!enabled)return; const c=findCollection(); if(!c)return; const cards=Array.from(c.children).filter(e=>e instanceof HTMLElement&&e.matches('.card')); const path=location.pathname.replace(/\/+$/,''); const current=cards.find(card=>Array.from(card.querySelectorAll('a[href*="/watch/"]')).some(a=>{try{return new URL(a.href,location.origin).pathname.replace(/\/+$/,'')===path}catch{return false}})); const currentNo=cardEpisodeNumber(current); for(const card of cards){ card.removeAttribute('data-better-crunchyroll-upcoming'); card.removeAttribute('data-better-crunchyroll-hide-title'); card.removeAttribute('data-better-crunchyroll-episode-label'); const n=cardEpisodeNumber(card); if(!Number.isFinite(currentNo)||!Number.isFinite(n)||n<=currentNo)continue; card.setAttribute('data-better-crunchyroll-upcoming','true'); card.setAttribute('data-better-crunchyroll-episode-label',`Episode ${n}`); if(settings.hideUpcomingTitles)card.setAttribute('data-better-crunchyroll-hide-title','true'); } }
  function findSkipButton(type){ const label={intro:'Skip Intro',recap:'Skip Recap',credits:'Skip Credits'}[type]; if(!label)return null; for(const selector of [`[aria-label="${label}"]`,`[title="${label}"]`]){const el=document.querySelector(selector);if(el&&visible(el))return el;} return null; }
  function skipActive(){ for(const type of ['intro','recap','credits']){const b=findSkipButton(type);if(b){b.click();return true;}} return false; }
  function autoSkip(type,on){ if(!enabled||!on)return; const b=findSkipButton(type); if(!b||autoSkipState.has(b))return; autoSkipState.add(b); b.click(); }
  function findNav(direction){ const label=direction==='next'?'Next Episode':'Previous Episode'; for(const selector of [`button[aria-label="${label}"]`,`a[aria-label="${label}"]`,`button[title="${label}"]`,`a[title="${label}"]`,`button[data-testid="${direction}-episode"]`,`a[data-testid="${direction}-episode"]`]){const el=document.querySelector(selector);if(el&&visible(el))return el;} return null; }
  function onKey(event){ if(!enabled||event.repeat||isTyping(event.target)||event.altKey||event.metaKey||event.ctrlKey)return; if(event.code===settings.shortcuts.skip){if(skipActive())event.preventDefault();}else if(event.code===settings.shortcuts.previous){const b=findNav('previous');if(b){event.preventDefault();b.click();}}else if(event.code===settings.shortcuts.next){const b=findNav('next');if(b){event.preventDefault();b.click();}} }
  function cleanup(){removeStyles();document.querySelectorAll('[data-better-crunchyroll-upcoming],[data-better-crunchyroll-hide-title],[data-better-crunchyroll-episode-label]').forEach(el=>['data-better-crunchyroll-upcoming','data-better-crunchyroll-hide-title','data-better-crunchyroll-episode-label'].forEach(a=>el.removeAttribute(a))); if(observer){observer.disconnect();observer=null;}}
  function refresh(){if(!enabled)return;injectStyles();updateSpoilers();autoSkip('intro',settings.autoSkipIntro);autoSkip('recap',settings.autoSkipRecap);autoSkip('credits',settings.autoSkipCredits);}
  function setEnabled(v){enabled=v!==false;if(!enabled){cleanup();return;}injectStyles();if(!observer){observer=new MutationObserver(refresh);observer.observe(document.documentElement,{childList:true,subtree:true});}refresh();}
  async function load(){const r=await chrome.storage.local.get({[STORAGE.enabled]:true,[STORAGE.shortcuts]:DEFAULTS.shortcuts,[STORAGE.autoSkipIntro]:false,[STORAGE.autoSkipRecap]:false,[STORAGE.autoSkipCredits]:false,[STORAGE.blurUpcoming]:false,[STORAGE.hideUpcomingTitles]:false});settings={shortcuts:{...DEFAULTS.shortcuts,...(r[STORAGE.shortcuts]||{})},autoSkipIntro:Boolean(r[STORAGE.autoSkipIntro]),autoSkipRecap:Boolean(r[STORAGE.autoSkipRecap]),autoSkipCredits:Boolean(r[STORAGE.autoSkipCredits]),blurUpcoming:Boolean(r[STORAGE.blurUpcoming]),hideUpcomingTitles:Boolean(r[STORAGE.hideUpcomingTitles])}; setEnabled(r[STORAGE.enabled]!==false);}
  document.addEventListener('keydown',onKey,true);
  chrome.storage.onChanged.addListener((changes,area)=>{if(area!=='local')return;if(changes[STORAGE.enabled])setEnabled(changes[STORAGE.enabled].newValue!==false);if(changes[STORAGE.shortcuts]||changes[STORAGE.autoSkipIntro]||changes[STORAGE.autoSkipRecap]||changes[STORAGE.autoSkipCredits]||changes[STORAGE.blurUpcoming]||changes[STORAGE.hideUpcomingTitles])load();});
  load();
})();
