(()=>{
const STORAGE={enabled:'betterCrunchyrollEnabled',shortcuts:'betterCrunchyrollShortcuts',autoSkipIntro:'betterCrunchyrollAutoSkipIntro',autoSkipRecap:'betterCrunchyrollAutoSkipRecap',autoSkipCredits:'betterCrunchyrollAutoSkipCredits',blurUpcoming:'betterCrunchyrollBlurUpcoming',hideUpcomingTitles:'betterCrunchyrollHideUpcomingTitles'};
const DEFAULTS={shortcuts:{skip:'KeyS',previous:'KeyP',next:'KeyN'},autoSkipIntro:false,autoSkipRecap:false,autoSkipCredits:false,blurUpcoming:false,hideUpcomingTitles:false};
const STYLE_ID='better-crunchyroll-v230-style',BLUR_ATTR='data-better-crunchyroll-blur-upcoming',TITLE_ATTR='data-better-crunchyroll-title-hidden',ORIGINAL_TITLE_ATTR='data-better-crunchyroll-original-title-v230';
let enabled=true,settings=structuredClone(DEFAULTS),observer=null,refreshTimer=null,lastUrl=location.href,lastSkip={intro:0,recap:0,credits:0};
const visible=e=>{if(!e)return false;const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0},isTyping=t=>{const g=t?.tagName?.toLowerCase();return g==='input'||g==='textarea'||g==='select'||t?.isContentEditable};
function injectStyles(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
.erc-episode-list-modal .erc-playable-collection > .card[${BLUR_ATTR}="true"] [class*="thumbnail-wrapper"]{overflow:hidden!important;border-radius:5px!important}
.erc-episode-list-modal .erc-playable-collection > .card[${BLUR_ATTR}="true"] [class*="thumbnail-wrapper"] img{filter:blur(10px)!important;transform:scale(1.045)!important;transform-origin:center!important}
.erc-episode-list-modal .erc-playable-collection > .card[${TITLE_ATTR}="true"] h3 [class*="title-link"],.erc-episode-list-modal .erc-playable-collection > .card[${TITLE_ATTR}="true"] h3{color:inherit!important}
`;(document.head||document.documentElement).appendChild(s)}
function removeStyles(){document.getElementById(STYLE_ID)?.remove()}
function getCollections(){const selectors=['.erc-episode-list-modal .erc-playable-collection.state-dt-condensed','.erc-episode-list-modal .erc-playable-collection','.erc-episode-list-modal [aria-label="Episodes in current season"] .erc-playable-collection'];const seen=new Set(),out=[];for(const q of selectors)for(const el of document.querySelectorAll(q))if(!seen.has(el)&&visible(el)){seen.add(el);out.push(el)}return out}
function cardsOf(c){return Array.from(c.querySelectorAll(':scope > .card, :scope > .cards-wrapper > .card, .card')).filter(e=>e instanceof HTMLElement)}
function cardEpisodeNumber(card){const t=card?.textContent||'',m=t.match(/\bE(?:pisode)?\s*(\d+)\b/i);return m?Number(m[1]):NaN}
function currentEpisodeCard(c){const path=location.pathname.replace(/\/+$/,'');const cards=cardsOf(c);return cards.find(card=>Array.from(card.querySelectorAll('a[href*="/watch/"]')).some(a=>{try{return new URL(a.href,location.origin).pathname.replace(/\/+$/,'')===path}catch{return false}}))||cards.find(card=>/NOW PLAYING/i.test(card.textContent||''))||null}
function titleElement(card){return card.querySelector('h3 a[class*="title-link"]')||card.querySelector('h3')||card.querySelector('[class*="playable-card__title"]')||card.querySelector('[class*="title"]')||null}
function restoreTitle(card){const t=titleElement(card);if(!t||!t.hasAttribute(TITLE_ATTR))return;const o=t.getAttribute(ORIGINAL_TITLE_ATTR);if(o!==null)t.textContent=o;t.removeAttribute(TITLE_ATTR);t.removeAttribute(ORIGINAL_TITLE_ATTR)}
function applyHiddenTitle(card,n){const t=titleElement(card);if(!t||!Number.isFinite(n))return;if(!t.hasAttribute(ORIGINAL_TITLE_ATTR))t.setAttribute(ORIGINAL_TITLE_ATTR,t.textContent||'');const r=`Episode ${n}`;if(t.textContent!==r)t.textContent=r;t.setAttribute(TITLE_ATTR,'true')}
function updateSpoilers(c){const cards=cardsOf(c),cur=currentEpisodeCard(c),curN=cardEpisodeNumber(cur);for(const card of cards){card.removeAttribute(BLUR_ATTR);if(!Number.isFinite(curN)){restoreTitle(card);continue}const n=cardEpisodeNumber(card),up=Number.isFinite(n)&&n>curN;if(up&&settings.hideUpcomingTitles)applyHiddenTitle(card,n);else restoreTitle(card);if(up&&settings.blurUpcoming)card.setAttribute(BLUR_ATTR,'true')}}
function updateAllEpisodeLists(){for(const c of getCollections())updateSpoilers(c)}
function observeEpisodeListContainers(){document.querySelectorAll('.erc-episode-list-modal').forEach(modal=>{if(modal.__betterCrunchyrollV230Observed)return;modal.__betterCrunchyrollV230Observed=true;const o=new MutationObserver(()=>{if(enabled)updateAllEpisodeLists()});o.observe(modal,{childList:true,subtree:true})})}
function processEpisodeCardsNow(){if(!enabled)return;observeEpisodeListContainers();updateAllEpisodeLists()}
function findMeaningButton(patterns){return Array.from(document.querySelectorAll('button,a,[role="button"]')).filter(visible).find(el=>{const text=[el.getAttribute('aria-label')||'',el.getAttribute('title')||'',el.textContent||''].join(' ').replace(/\s+/g,' ').trim();return patterns.some(p=>p.test(text))})||null}
function findSkipButton(type){const p={intro:[/^\s*skip\s+intro\s*$/i,/skip\s+intro/i],recap:[/^\s*skip\s+recap\s*$/i,/skip\s+recap/i],credits:[/^\s*skip\s+credits\s*$/i,/skip\s+credits/i]};return findMeaningButton(p[type]||[])}
function skipActive(){for(const t of ['intro','recap','credits']){const b=findSkipButton(t);if(b){b.click();return true}}return false}
function autoSkip(type,flag){if(!enabled||!flag)return;const b=findSkipButton(type);if(!b)return;const now=Date.now();if(now-lastSkip[type]<1600)return;lastSkip[type]=now;b.click()}
function findEpisodeNav(d){const patterns=d==='next'?[/^\s*next\s+episode\s*$/i,/next\s+episode/i]:[/^\s*previous\s+episode\s*$/i,/previous\s+episode/i];return findMeaningButton(patterns)}
function handleShortcut(e){if(!enabled||e.repeat||isTyping(e.target)||e.altKey||e.ctrlKey||e.metaKey)return;if(e.code===settings.shortcuts.skip){if(skipActive())e.preventDefault();return}if(e.code===settings.shortcuts.previous){const b=findEpisodeNav('previous');if(b){e.preventDefault();b.click()}return}if(e.code===settings.shortcuts.next){const b=findEpisodeNav('next');if(b){e.preventDefault();b.click()}}}
function removeEnhancements(){removeStyles();document.querySelectorAll(`[${BLUR_ATTR}="true"]`).forEach(e=>e.removeAttribute(BLUR_ATTR));document.querySelectorAll(`[${TITLE_ATTR}="true"]`).forEach(t=>{const o=t.getAttribute(ORIGINAL_TITLE_ATTR);if(o!==null)t.textContent=o;t.removeAttribute(TITLE_ATTR);t.removeAttribute(ORIGINAL_TITLE_ATTR)});lastSkip={intro:0,recap:0,credits:0}}
function refresh(){if(!enabled)return;injectStyles();observeEpisodeListContainers();updateAllEpisodeLists();autoSkip('intro',settings.autoSkipIntro);autoSkip('recap',settings.autoSkipRecap);autoSkip('credits',settings.autoSkipCredits)}
function scheduleRefresh(d=0){if(!enabled)return;clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{refresh();for(const ms of [100,300,700,1500])setTimeout(()=>{if(enabled)refresh()},ms)},d)}
function detectNavigation(){if(location.href!==lastUrl){lastUrl=location.href;scheduleRefresh(0)}}
function setEnabled(next){enabled=next!==false;if(!enabled){removeEnhancements();if(observer){observer.disconnect();observer=null}return}injectStyles();if(!observer){observer=new MutationObserver(()=>scheduleRefresh(25));observer.observe(document.documentElement,{childList:true,subtree:true})}scheduleRefresh(0)}
async function loadSettings(){const st=await chrome.storage.local.get({[STORAGE.enabled]:true,[STORAGE.shortcuts]:DEFAULTS.shortcuts,[STORAGE.autoSkipIntro]:false,[STORAGE.autoSkipRecap]:false,[STORAGE.autoSkipCredits]:false,[STORAGE.blurUpcoming]:false,[STORAGE.hideUpcomingTitles]:false});settings={shortcuts:{...DEFAULTS.shortcuts,...(st[STORAGE.shortcuts]||{})},autoSkipIntro:Boolean(st[STORAGE.autoSkipIntro]),autoSkipRecap:Boolean(st[STORAGE.autoSkipRecap]),autoSkipCredits:Boolean(st[STORAGE.autoSkipCredits]),blurUpcoming:Boolean(st[STORAGE.blurUpcoming]),hideUpcomingTitles:Boolean(st[STORAGE.hideUpcomingTitles])};setEnabled(st[STORAGE.enabled]!==false)}
for(const method of ['pushState','replaceState']){const original=history[method];history[method]=function(...args){const r=original.apply(this,args);window.dispatchEvent(new Event('better-crunchyroll-v230-navigation'));return r}}
window.addEventListener('better-crunchyroll-v230-navigation',detectNavigation);window.addEventListener('popstate',detectNavigation);window.addEventListener('hashchange',detectNavigation);setInterval(detectNavigation,500);
document.addEventListener('click',e=>{if(!enabled)return;const t=e.target?.closest?.('button,a,[role="button"]');if(!t)return;const text=[t.getAttribute('aria-label')||'',t.getAttribute('title')||'',t.textContent||''].join(' ').replace(/\s+/g,' ').trim();if(/episode|episodes/i.test(text)){setTimeout(processEpisodeCardsNow,0);setTimeout(processEpisodeCardsNow,100);setTimeout(processEpisodeCardsNow,350);setTimeout(processEpisodeCardsNow,900)}},true);
document.addEventListener('keydown',handleShortcut,true);
chrome.storage.onChanged.addListener((changes,area)=>{if(area!=='local')return;if(changes[STORAGE.enabled])setEnabled(changes[STORAGE.enabled].newValue!==false);if(changes[STORAGE.shortcuts]||changes[STORAGE.autoSkipIntro]||changes[STORAGE.autoSkipRecap]||changes[STORAGE.autoSkipCredits]||changes[STORAGE.blurUpcoming]||changes[STORAGE.hideUpcomingTitles])loadSettings()});
loadSettings();})();